# Generated by Django 5.1.1 on 2024-09-26 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_at', models.DateTimeField()),
                ('headcount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirm'), ('CC', 'Canceled'), ('NS', 'No Show')], default='PD')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
