# Generated by Django 5.1.1 on 2024-10-07 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirm'), ('CC', 'Canceled'), ('NS', 'No Show'), ('ET', 'Entered')], default='PD'),
        ),
    ]
